<a href="https://colab.research.google.com/github/custom-hyper/Analytics/blob/main/breadth_thrust.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# "When the time comes to buy, you won't want to" - Walter Deemer

# What is a Breadth Thrust?

"The Breadth Thrust Indicator is a technical indicator used to ascertain market momentum. It is computed by calculating the number of advancing issues on an exchange, such as the New York Stock Exchange (NYSE), divided by the total number of issues (advancing + declining) on it, and generating a 10-day moving average of this percentage."

https://www.investopedia.com/terms/b/breadth-thrust-indicator.asp

# Zweig Breadth Thrust



The Zweig Breadth Thrust is an indicator that measures a change in market momentum during a compressed period. A Zweig Breadth Thrust occurs when the Breadth Thrust indicator rises from below 40 percent to above 61.5 percent.

There is a [TradingView PineScript by LazyBear](https://www.tradingview.com/script/NcNA4SUf-Zweig-Market-Breadth-Thrust-Indicator-LazyBear/) that we can use to see this on a chart. 

![](https://i.imgur.com/zxC7I4w.png)

The following article on [Humble Student of the Markets](https://humblestudentofthemarkets.com/2019/01/07/a-rare-what-my-credit-card-limit-buy-signal/) describes the history of the Zweig Breadth Thrust and highlights the occurrence on January 7, 2019.

## How do we code this in Python?

We can programmatically get a list of NYSE-traded stocks using the Alpaca API or by downloading a [CSV file from NASDAQ](https://www.nasdaq.com/market-activity/stocks/screener)

In [ ]:
from getpass import getpass

API_KEY = getpass('Enter your API KEY: ')
SECRET_KEY = getpass('Enter your SECRET KEY: ')

Enter your API KEY: ··········
Enter your SECRET KEY: ··········

In [ ]:
!pip install alpaca-trade-api

Collecting alpaca-trade-api
  Downloading alpaca_trade_api-2.0.0-py3-none-any.whl (33 kB)
Requirement already satisfied: requests<3,>2 in /usr/local/lib/python3.7/dist-packages (from alpaca-trade-api) (2.23.0)
Collecting deprecation==2.1.0
  Downloading deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting websocket-client<2,>=0.56.0
  Downloading websocket_client-1.3.2-py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 2.4 MB/s
Collecting websockets<11,>=9.0
  Downloading websockets-10.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (111 kB)
     |████████████████████████████████| 111 kB 16.6 MB/s
Collecting aiohttp==3.8.1
  Downloading aiohttp-3.8.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 60.7 MB/s
Requirement already satisfied: urllib3<2,>1.24 in /usr/local/lib/python3.7/dist-packages (from alpaca-trade-api) (1.24.3)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.7/dist-packages (from alpaca-trade-api) (1.21.5)
Requirement already satisfied: pandas>=0.18.1 in /usr/local/lib/python3.7/dist-packages (from alpaca-trade-api) (1.3.5)
Requirement already satisfied: msgpack==1.0.3 in /usr/local/lib/python3.7/dist-packages (from alpaca-trade-api) (1.0.3)
Collecting PyYAML==6.0
  Downloading PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
     |████████████████████████████████| 596 kB 45.6 MB/s
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
     |████████████████████████████████| 144 kB 58.8 MB/s
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.8.1->alpaca-trade-api) (21.4.0)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (271 kB)
     |████████████████████████████████| 271 kB 47.3 MB/s
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.8.1->alpaca-trade-api) (4.1.1)
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.2-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (94 kB)
     |████████████████████████████████| 94 kB 3.8 MB/s
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp==3.8.1->alpaca-trade-api) (2.0.12)
Collecting asynctest==0.13.0
  Downloading asynctest-0.13.0-py3-none-any.whl (26 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from deprecation==2.1.0->alpaca-trade-api) (21.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.18.1->alpaca-trade-api) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.18.1->alpaca-trade-api) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3,>2->alpaca-trade-api) (2021.10.8)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3,>2->alpaca-trade-api) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3,>2->alpaca-trade-api) (3.0.4)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->deprecation==2.1.0->alpaca-trade-api) (3.0.8)
Installing collected packages: multidict, frozenlist, yarl, asynctest, async-timeout, aiosignal, websockets, websocket-client, PyYAML, deprecation, aiohttp, alpaca-trade-api
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
Successfully installed PyYAML-6.0 aiohttp-3.8.1 aiosignal-1.2.0 alpaca-trade-api-2.0.0 async-timeout-4.0.2 asynctest-0.13.0 deprecation-2.1.0 frozenlist-1.3.0 multidict-6.0.2 websocket-client-1.3.2 websockets-10.2 yarl-1.7.2

In [ ]:
import pandas
import numpy as np
from alpaca_trade_api.rest import REST, TimeFrame

alpaca = REST(API_KEY, SECRET_KEY, 'https://paper-api.alpaca.markets')

assets = alpaca.list_assets()

symbols = []
for asset in assets:
    if asset.exchange == 'NYSE' and asset.status == 'active':
        symbols.append(asset.symbol)

symbols

['AAQC.U',
 'AAT',
 'AAP',
 'AAQC',
 'AC',
 'AEG',
 'ACC',
 'ACCO',
 'ACDI.U',
 'ACEL',
 'ACH',
 'ACRO.U',
 'ADX',
 'AEFC',
 'AES',
 'AESC',
 'AEVA',
 'AFB',
 'AG',
 'AGCB',
 'AXR',
 'AGL',
 'AGM',
 'AGM.A',
 'BHK',
 'AKA',
 'ALC',
 'ALCC',
 'ALE',
 'AM',
 'AMAM',
 'AMBC',
 'AMBP',
 'AMRX',
 'AMTD',
 'ANET',
 'APGB.U',
 'APRN',
 'APSG',
 'APTS',
 'APTV',
 'ARC',
 'ARI',
 'ARNC',
 'AROC',
 'ARR',
 'ASG',
 'ASR',
 'ATA.U',
 'ATO',
 'AVB',
 'AVD',
 'AX',
 'AXAC',
 'AXAC.RT',
 'BANC',
 'BBAR',
 'BBU',
 'BBUC',
 'BBVA',
 'BBW',
 'BBWI',
 'BEKE',
 'BEPI',
 'DTE',
 'BFH',
 'BGS',
 'BGSF',
 'BGSX',
 'BHIL',
 'BHLB',
 'BHP',
 'BHR',
 'BHV',
 'BHVN',
 'BIO',
 'BIO.B',
 'BIP',
 'BIPC',
 'BME',
 'BMEZ',
 'BMI',
 'BOE',
 'BOH',
 'EXPR',
 'BRDG',
 'BRO',
 'BSL',
 'BSM',
 'BV',
 'BVH',
 'BVN',
 'BWXT',
 'BZH',
 'C',
 'CAAP',
 'CADE',
 'CAE',
 'CAF',
 'CALX',
 'CAJ',
 'CARR',
 'CARS',
 'CAS.U',
 'CATO',
 'CAT',
 'CBL',
 'CBT',
 'CCM',
 'CCO',
 'CCS',
 'CCU',
 'CCV',
 'CCV.U',
 'CCVI',
 'CCVI.U',
 'CCZ',
 'CDAY',
 'CDE',
 'CEA',
 'CEE',
 'CEIX',
 'CELG.RT',
 'CELP',
 'CEM',
 'CEN',
 'CEPU',
 'CEQP',
 'CCJ',
 'CCK',
 'CCL',
 'CF',
 'CFR',
 'CGA',
 'CGAU',
 'GL',
 'CHMI',
 'CHRA',
 'CHRB',
 'CIA',
 'CIAN',
 'CIB',
 'CIF',
 'CIG',
 'CII',
 'CINT',
 'CLAA',
 'CLAA.U',
 'CLAS',
 'CLAS.U',
 'CLB',
 'CLBR',
 'CLBR.U',
 'CLF',
 'CLH',
 'CLS',
 'CMA',
 'CMC',
 'CMG',
 'CMU',
 'CNA',
 'CND.U',
 'CNDA.U',
 'CNDB',
 'CNDB.U',
 'CNHI',
 'CNI',
 'CNS',
 'CNX',
 'CODI',
 'COLD',
 'CORR',
 'CORS',
 'CORS.U',
 'COTY',
 'CP',
 'CPA',
 'CPAC',
 'CPS',
 'CPTK',
 'CPTK.U',
 'CPUH',
 'CR',
 'CRK',
 'CRT',
 'CSR',
 'CSTM',
 'CSV',
 'CTBB',
 'CTDD',
 'CTS',
 'CTT',
 'CUBB',
 'CUBE',
 'CUBI',
 'CURO',
 'CURV',
 'CUZ',
 'CVEO',
 'CVI',
 'CVS',
 'CVX',
 'CW',
 'CWEN',
 'CWEN.A',
 'CX',
 'CXAC',
 'CXAC.U',
 'CYH',
 'DAO',
 'DAR',
 'DASH',
 'DAVA',
 'DB',
 'DBD',
 'FRC',
 'DBI',
 'DBRG',
 'DCP',
 'DEX',
 'DFP',
 'DFS',
 'DGX',
 'DHT',
 'DHX',
 'DIAX',
 'DIDI',
 'DINO',
 'DIS',
 'HDB',
 'DK',
 'DLR',
 'DLY',
 'DM',
 'DMA',
 'DMB',
 'DMO',
 'DMS',
 'DMYS',
 'DOCN',
 'DOCS',
 'DOUG',
 'DOV',
 'DPG',
 'DRD',
 'DRE',
 'DRH',
 'DTF',
 'DTG',
 'DTW',
 'DUK',
 'DV',
 'DWIN',
 'DWIN.U',
 'DX',
 'DXC',
 'EAI',
 'EARN',
 'EAT',
 'EBF',
 'ECCW',
 'ECCX',
 'ECOM',
 'ECVT',
 'EDI',
 'EDU',
 'EEX',
 'EFC',
 'EFR',
 'EFX',
 'EGF',
 'EGO',
 'EGP',
 'EIC',
 'EICA',
 'EIG',
 'EIX',
 'ELAN',
 'ELAT',
 'ELC',
 'ELP',
 'ELS',
 'EMN',
 'ENB',
 'ENBA',
 'ENIC',
 'ENJ',
 'ENLC',
 'ENOV',
 'ENPC',
 'ENPC.U',
 'ENR',
 'ENV',
 'ENVA',
 'ENZ',
 'EOCW',
 'EOCW.U',
 'EOD',
 'EOG',
 'EOI',
 'EPAC',
 'EPAM',
 'EPC',
 'EPD',
 'EPRT',
 'EPWR.U',
 'EQC',
 'EQD',
 'EQD.U',
 'EQH',
 'EQHA',
 'EQHA.U',
 'EQR',
 'EQS',
 'EQT',
 'ERJ',
 'ESE',
 'ESGC',
 'ESI',
 'ESM',
 'ESM.U',
 'ESMT',
 'ESRT',
 'ESS',
 'ETB',
 'ETO',
 'ETV',
 'ETW',
 'ETWO',
 'EVA',
 'EVC',
 'EVE',
 'EVE.U',
 'EVF',
 'EVG',
 'EVR',
 'EVRG',
 'EVRI',
 'EVTL',
 'EXG',
 'EXK',
 'EXR',
 'F',
 'FACT.U',
 'FAF',
 'FATH',
 'FBC',
 'FBHS',
 'FBK',
 'FBP',
 'FCAX',
 'FCAX.U',
 'FCF',
 'FCN',
 'FCRX',
 'FCT',
 'FDP',
 'FDS',
 'FDX',
 'FE',
 'FEDU',
 'FF',
 'FFA',
 'FFC',
 'FICO',
 'FIGS',
 'FINV',
 'FIS',
 'FIX',
 'FLC',
 'FLME',
 'FLME.U',
 'FLS',
 'FLT',
 'FLYA',
 'FLYA.U',
 'FMX',
 'FNA',
 'FNB',
 'FND',
 'FOA',
 'FOE',
 'FOF',
 'FOR',
 'FORG',
 'FPF',
 'FPH',
 'FREY',
 'FRT',
 'FSLY',
 'FSM',
 'FSNB',
 'FSNB.U',
 'FST',
 'FST.U',
 'FT',
 'FTAI',
 'FTHY',
 'FUBO',
 'FVIV',
 'FVIV.U',
 'FVRR',
 'FVT',
 'FVT.U',
 'FXLV',
 'G',
 'GAB',
 'GAM',
 'GAPA',
 'GAPA.U',
 'GATO',
 'GATX',
 'GB',
 'GBAB',
 'GBLI',
 'GBLL',
 'GBX',
 'GDDY',
 'GDL',
 'GDO',
 'GDOT',
 'GE',
 'GEF',
 'GEF.B',
 'GEL',
 'GEO',
 'GER',
 'GFF',
 'GFL',
 'GGZ',
 'GHG',
 'GHM',
 'GHY',
 'GIA',
 'GIA.U',
 'GIB',
 'GIM',
 'GKOS',
 'GLS',
 'GME',
 'GMED',
 'GNRC',
 'GNT',
 'GOF',
 'GOGN',
 'GOGN.U',
 'GOL',
 'GOLD',
 'GOLF',
 'GOOS',
 'GPMT',
 'GPN',
 'GPOR',
 'GRMN',
 'GRP.U',
 'GSQB',
 'GSQB.U',
 'GSQD',
 'GSQD.U',
 'GUG',
 'GWW',
 'HAE',
 'HAYW',
 'HBM',
 'HESM',
 'HGTY',
 'HII',
 'HIL',
 'HIMS',
 'HIX.RT',
 'HPE',
 'HPF',
 'HPI',
 'HUBB',
 'HUBS',
 'HYI',
 'HYLN',
 'IBA',
 'IBER',
 'IBER.U',
 'IBM',
 'IDA',
 'IHG',
 'INSW',
 'INT',
 'INVH',
 'IPOF',
 'IQV',
 'IR',
 'IVC',
 'IVZ',
 'JEMD',
 'JHI',
 'JKS',
 'JP',
 'JPC',
 'JPI',
 'JPM',
 'JWSM',
 'KMF',
 'KRC',
 'KREF',
 'KRG',
 'KSM',
 'KW',
 'LADR',
 'LBRT',
 'LC',
 'LCW.U',
 'LEG',
 'LEN',
 'LGV.U',
 'LIN',
 'LOKM',
 'LOKM.U',
 'LOMA',
 'LUB',
 'LUMN',
 'LXFR',
 'LXP',
 'MC',
 'MGU',
 'MNTN',
 'MNTN.U',
 'MOG.A',
 'MOGU',
 'MPV',
 'MPW',
 'MPX',
 'MVO',
 'UL',
 'NFYS',
 'NFYS.U',
 'NGC',
 'NID',
 'NIE',
 'V',
 'NR',
 'NRZ',
 'NTST',
 'NUVB',
 'NVO',
 'NVR',
 'OCFT',
 'OFG',
 'ONL',
 'ONON',
 'OPAD',
 'OR',
 'ORA',
 'OSI',
 'OXY',
 'PAC',
 'PAM',
 'PAY',
 'PAYC',
 'PB',
 'PBA',
 'PBR',
 'PDI',
 'PDM',
 'PDO',
 'PDOT',
 'PDOT.U',
 'PEI',
 'PFE',
 'PFH',
 'PFL',
 'PFN',
 'PFO',
 'PFS',
 'PFSI',
 'PINE',
 'PING',
 'PINS',
 'PNC',
 'POLY',
 'POND',
 'PSFE',
 'PSTG',
 'PSTH',
 'ACDI',
 'ADC',
 'ADCT',
 'ADNT',
 'AEE',
 'GFLU',
 'GFOR',
 'NU',
 'PVL',
 'QS',
 'QUOT',
 'RBA',
 'RBAC',
 'RCC',
 'RCFA.U',
 'RDN',
 'REV',
 'REVG',
 'RFL',
 'RFM',
 'RHP',
 'RIV',
 'RJAC',
 'RJAC.U',
 'RJF',
 'RNP',
 'RONI.U',
 'ROP',
 'ROSS',
 'ROSS.U',
 'RRC',
 'RRX',
 'RVT',
 'S',
 'SAM',
 'SAN',
 'SBSW',
 'SCI',
 'SCL',
 'SCM',
 'SCU',
 'SCUA',
 'SCUA.U',
 'SCX',
 'SDHY',
 'SE',
 'SEMR',
 'SHW',
 'SII',
 'SIX',
 'SJIV',
 'SKM',
 'ACN',
 'ACP',
 'ACR',
 'ACRE',
 'ACRO',
 'EE',
 'CE',
 'CHS',
 'CMI',
 'CXW',
 'DBL',
 'GHC',
 'PSTL',
 'SNDA',
 'SNDR',
 'SNV',
 'SNX',
 'SO',
 'SPG',
 'SPGI',
 'SPGS',
 'SPGS.U',
 'SPH',
 'SPIR',
 'SPLP',
 'SPXC',
 'SPXX',
 'SQM',
 'SQNS',
 'SRI',
 'SRL',
 'SRLP',
 'STE',
 'STEM',
 'STNG',
 'STON',
 'STOR',
 'TEF',
 'TEI',
 'TEL',
 'TFII',
 'THW',
 'TISI',
 'TIXT',
 'TMHC',
 'AAN',
 'TR',
 'TREX',
 'TRGP',
 'TRI',
 'TTC',
 'TWTR',
 'TX',
 'USER',
 'USFD',
 'USM',
 'USNA',
 'UTI',
 'UTL',
 'UVV',
 'UWMC',
 'UZF',
 'VAC',
 'VCV',
 'VIAO',
 'VIPS',
 'VLD',
 'VLT',
 'VLTA',
 'VNO',
 'VSH',
 'VYGG.U',
 'WBS',
 'WBT',
 'WES',
 'WIW',
 'WK',
 'WMT',
 'WNC',
 'WSO.B',
 'WSR',
 'WST',
 'WU',
 'XIN',
 'XPEV',
 'XPO',
 'XPOA',
 'XPOA.U',
 'XPOF',
 'XPRO',
 'YALA',
 'YELP',
 'ZME',
 'ZUO',
 'ZVIA',
 'CRI',
 'BLD',
 'COP',
 'MOG.B',
 'UNVR',
 'VTEX',
 'ZYME',
 'CULP',
 'DAN',
 'EC',
 'HD',
 'LAD',
 'PATH',
 'SRE',
 'W',
 'AAC',
 'AAC.U',
 'AAIC',
 'AAIN',
 'BP',
 'FRO',
 'PL',
 'BMA',
 'DCUE',
 'AB',
 'ABB',
 'ABBV',
 'ABC',
 'ABEV',
 'ABG',
 'ABM',
 'ABR',
 'ABT',
 'ACA',
 'ACAQ',
 'ACAQ.U',
 'ACHR',
 'ACI',
 'ACII',
 'ACII.U',
 'ACM',
 'ACV',
 'ADEX',
 'ADEX.U',
 'ADM',
 'ADT',
 'AEL',
 'AEM',
 'AENZ',
 'AEO',
 'AER',
 'AFG',
 'AFGB',
 'AFGC',
 'AFGD',
 'AFGE',
 'AFI',
 'AFL',
 'AFT',
 'AFTR',
 'AFTR.U',
 'AGAC',
 'AGAC.U',
 'AGCO',
 'AGD',
 'AGI',
 'AGO',
 'AGR',
 'AGRO',
 'AGS',
 'AGTI',
 'AGX',
 'AHH',
 'AHT',
 'AI',
 'AIC',
 'AIF',
 'AIG',
 'AIN',
 'AIO',
 'AIR',
 'AIRC',
 'AIT',
 'AIV',
 'AIZ',
 'AIZN',
 'AJG',
 'AJRD',
 'AJX',
 'AJXA',
 'AKO.A',
 'AKO.B',
 'AKR',
 'AL',
 'ALB',
 'ALEX',
 'ALG',
 'ALIT',
 'ALK',
 'ALL',
 'ALLE',
 'ALLG',
 'ALLY',
 'ALSN',
 'ALV',
 'ALX',
 'AMC',
 'AMCR',
 'AME',
 'AMG',
 'AMH',
 'AMK',
 'AMN',
 'AMOV',
 'AMP',
 'AMPI',
 'AMPI.U',
 'AMPS',
 'AMPY',
 'AMR',
 'AMRC',
 'AMT',
 'AMWL',
 'AMX',
 'AN',
 'ANAC',
 'ANAC.U',
 'ANF',
 'ANTM',
 'ANVS',
 'AOD',
 'AOMR',
 'AON',
 'AORT',
 'AOS',
 'AP',
 'APAM',
 'APCA',
 'APCA.U',
 'APD',
 'APG',
 'APGB',
 'APH',
 'APLE',
 'APN',
 'APN.U',
 'APO',
 'APSG.U',
 'AQN',
 'AQNA',
 'AQNB',
 'AQNU',
 'AQUA',
 'AR',
 'ARCH',
 'ARCO',
 'ARDC',
 'ARE',
 'ARES',
 'ARGD',
 'ARGO',
 'ARIS',
 'ARL',
 'ARLO',
 'ARMK',
 'ARW',
 'ASA',
 'ASAI',
 'ASAN',
 'ASAQ',
 'ASAQ.U',
 'ASB',
 'ASC',
 'ASGI',
 'ASGN',
 'ASH',
 'ASIX',
 'ASPN',
 'ASX',
 'ASZ',
 'ASZ.U',
 'ATA',
 'ATAQ',
 'ATAQ.U',
 'ATC',
 'ATCO',
 'ATEK',
 'ATEK.U',
 'ATEN',
 'ATGE',
 'ATHM',
 'ATI',
 'ATIP',
 'ATKR',
 'ATR',
 'ATTO',
 'ATUS',
 'AU',
 'AUD',
 'AUS',
 'AUS.U',
 'AUY',
 'AVA',
 'AVAL',
 'AVAN',
 'AVAN.U',
 'AVK',
 'AVLR',
 'AVNS',
 'AVNT',
 'AVTR',
 'AVY',
 'AVYA',
 'AWF',
 'AWI',
 'AWK',
 'AWP',
 'AWR',
 'AXH',
 'AXH.U',
 'AXL',
 'AXP',
 'AXS',
 'AXTA',
 'AYI',
 'AYX',
 'AZEK',
 'AZO',
 'AZRE',
 'AZUL',
 'AZZ',
 'B',
 'BA',
 'BABA',
 'BAC',
 'BACA',
 'BACA.U',
 'BAH',
 'BAK',
 'BALY',
 'BAM',
 'BAMH',
 'BAMI',
 'BAMR',
 'BAP',
 'BARK',
 'BAX',
 'BB',
 'BBAI',
 'BBD',
 'BBDC',
 'BBDO',
 'BBLN',
 'BBN',
 'BBY',
 'BC',
 'BCAT',
 'BCC',
 'BCE',
 'BCH',
 'BCO',
 'BCS',
 'BCSF',
 'BCX',
 'BDC',
 'BDJ',
 'BDN',
 'BDX',
 'BDXB',
 'BE',
 'BEDU',
 'BEN',
 ...]

In [ ]:
bars = alpaca.get_bars(symbols, TimeFrame.Day, "2018-12-01", "2019-01-10").df
print(bars)

                            open     high      low  close   volume  \
timestamp
2018-12-03 05:00:00+00:00  32.80  33.4691  31.7800  32.05  2946286
2018-12-04 05:00:00+00:00  32.11  32.1900  30.2700  30.40  3037998
2018-12-06 05:00:00+00:00  29.25  29.6800  28.1200  29.65  4244173
2018-12-07 05:00:00+00:00  30.20  30.2100  28.6796  28.82  3383928
2018-12-10 05:00:00+00:00  28.64  29.1400  27.8500  28.32  2915624
...                          ...      ...      ...    ...      ...
2019-01-04 05:00:00+00:00  14.36  15.2300  14.2100  14.92   127075
2019-01-07 05:00:00+00:00  15.08  15.6100  14.9500  15.50   191648
2019-01-08 05:00:00+00:00  15.95  15.9500  14.9600  15.53   156602
2019-01-09 05:00:00+00:00  15.70  15.8500  15.1400  15.57   146683
2019-01-10 05:00:00+00:00  15.60  15.9300  15.4200  15.80   105156

                           trade_count       vwap symbol
timestamp
2018-12-03 05:00:00+00:00        15585  32.505452     AA
2018-12-04 05:00:00+00:00        19461  30.938960     AA
2018-12-06 05:00:00+00:00        24094  29.134131     AA
2018-12-07 05:00:00+00:00        22391  29.256260     AA
2018-12-10 05:00:00+00:00        18617  28.347607     AA
...                                ...        ...    ...
2019-01-04 05:00:00+00:00          853  14.958786   ZYME
2019-01-07 05:00:00+00:00         1105  15.321471   ZYME
2019-01-08 05:00:00+00:00         1241  15.426928   ZYME
2019-01-09 05:00:00+00:00         1325  15.576926   ZYME
2019-01-10 05:00:00+00:00         1007  15.738794   ZYME

[54307 rows x 8 columns]

In [ ]:
bars['pct_change'] = bars['close'].pct_change()
bars['sign'] = np.sign(bars['pct_change'])
print(bars)

                            open     high      low  close   volume  \
timestamp
2018-12-03 05:00:00+00:00  32.80  33.4691  31.7800  32.05  2946286
2018-12-04 05:00:00+00:00  32.11  32.1900  30.2700  30.40  3037998
2018-12-06 05:00:00+00:00  29.25  29.6800  28.1200  29.65  4244173
2018-12-07 05:00:00+00:00  30.20  30.2100  28.6796  28.82  3383928
2018-12-10 05:00:00+00:00  28.64  29.1400  27.8500  28.32  2915624
...                          ...      ...      ...    ...      ...
2019-01-04 05:00:00+00:00  14.36  15.2300  14.2100  14.92   127075
2019-01-07 05:00:00+00:00  15.08  15.6100  14.9500  15.50   191648
2019-01-08 05:00:00+00:00  15.95  15.9500  14.9600  15.53   156602
2019-01-09 05:00:00+00:00  15.70  15.8500  15.1400  15.57   146683
2019-01-10 05:00:00+00:00  15.60  15.9300  15.4200  15.80   105156

                           trade_count       vwap symbol  pct_change  sign
timestamp
2018-12-03 05:00:00+00:00        15585  32.505452     AA         NaN   NaN
2018-12-04 05:00:00+00:00        19461  30.938960     AA   -0.051482  -1.0
2018-12-06 05:00:00+00:00        24094  29.134131     AA   -0.024671  -1.0
2018-12-07 05:00:00+00:00        22391  29.256260     AA   -0.027993  -1.0
2018-12-10 05:00:00+00:00        18617  28.347607     AA   -0.017349  -1.0
...                                ...        ...    ...         ...   ...
2019-01-04 05:00:00+00:00          853  14.958786   ZYME    0.064194   1.0
2019-01-07 05:00:00+00:00         1105  15.321471   ZYME    0.038874   1.0
2019-01-08 05:00:00+00:00         1241  15.426928   ZYME    0.001935   1.0
2019-01-09 05:00:00+00:00         1325  15.576926   ZYME    0.002576   1.0
2019-01-10 05:00:00+00:00         1007  15.738794   ZYME    0.014772   1.0

[54307 rows x 10 columns]

In [ ]:
df = bars.groupby(by = ['timestamp', 'sign'])['sign'].count().to_frame('count').reset_index()
df

                   timestamp  sign  count
0  2018-12-03 05:00:00+00:00  -1.0   1016
1  2018-12-03 05:00:00+00:00   0.0      1
2  2018-12-03 05:00:00+00:00   1.0   1066
3  2018-12-04 05:00:00+00:00  -1.0   1748
4  2018-12-04 05:00:00+00:00   0.0     55
..                       ...   ...    ...
73 2019-01-09 05:00:00+00:00   0.0     95
74 2019-01-09 05:00:00+00:00   1.0   1470
75 2019-01-10 05:00:00+00:00  -1.0    729
76 2019-01-10 05:00:00+00:00   0.0     99
77 2019-01-10 05:00:00+00:00   1.0   1264

[78 rows x 3 columns]

In [ ]:
df = pandas.pivot_table(df, values = 'count', index=['timestamp'], columns = 'sign')
df

sign                       -1.0   0.0   1.0
timestamp
2018-12-03 05:00:00+00:00  1016     1  1066
2018-12-04 05:00:00+00:00  1748    55   281
2018-12-06 05:00:00+00:00  1202    75   808
2018-12-07 05:00:00+00:00  1496    91   498
2018-12-10 05:00:00+00:00  1366    84   636
2018-12-11 05:00:00+00:00  1155    91   840
2018-12-12 05:00:00+00:00   654    79  1354
2018-12-13 05:00:00+00:00  1317    97   673
2018-12-14 05:00:00+00:00  1642    89   356
2018-12-17 05:00:00+00:00  1770    67   250
2018-12-18 05:00:00+00:00  1032    86   969
2018-12-19 05:00:00+00:00  1574    66   448
2018-12-20 05:00:00+00:00  1651    76   362
2018-12-21 05:00:00+00:00  1653    65   371
2018-12-24 05:00:00+00:00  1597    89   404
2018-12-26 05:00:00+00:00   195    69  1826
2018-12-27 05:00:00+00:00   824    94  1172
2018-12-28 05:00:00+00:00   873    87  1131
2018-12-31 05:00:00+00:00   590    75  1426
2019-01-02 05:00:00+00:00   702    69  1321
2019-01-03 05:00:00+00:00  1301    83   708
2019-01-04 05:00:00+00:00   165    66  1861
2019-01-07 05:00:00+00:00   405    57  1630
2019-01-08 05:00:00+00:00   368    72  1652
2019-01-09 05:00:00+00:00   527    95  1470
2019-01-10 05:00:00+00:00   729    99  1264

In [ ]:
df = df.rename(columns={1.0: "advancers", 0.0: "unchanged", -1.0: "decliners"})
df

sign                       decliners  unchanged  advancers
timestamp
2018-12-03 05:00:00+00:00       1016          1       1066
2018-12-04 05:00:00+00:00       1748         55        281
2018-12-06 05:00:00+00:00       1202         75        808
2018-12-07 05:00:00+00:00       1496         91        498
2018-12-10 05:00:00+00:00       1366         84        636
2018-12-11 05:00:00+00:00       1155         91        840
2018-12-12 05:00:00+00:00        654         79       1354
2018-12-13 05:00:00+00:00       1317         97        673
2018-12-14 05:00:00+00:00       1642         89        356
2018-12-17 05:00:00+00:00       1770         67        250
2018-12-18 05:00:00+00:00       1032         86        969
2018-12-19 05:00:00+00:00       1574         66        448
2018-12-20 05:00:00+00:00       1651         76        362
2018-12-21 05:00:00+00:00       1653         65        371
2018-12-24 05:00:00+00:00       1597         89        404
2018-12-26 05:00:00+00:00        195         69       1826
2018-12-27 05:00:00+00:00        824         94       1172
2018-12-28 05:00:00+00:00        873         87       1131
2018-12-31 05:00:00+00:00        590         75       1426
2019-01-02 05:00:00+00:00        702         69       1321
2019-01-03 05:00:00+00:00       1301         83        708
2019-01-04 05:00:00+00:00        165         66       1861
2019-01-07 05:00:00+00:00        405         57       1630
2019-01-08 05:00:00+00:00        368         72       1652
2019-01-09 05:00:00+00:00        527         95       1470
2019-01-10 05:00:00+00:00        729         99       1264

In [ ]:
df['percent_advancing'] = df['advancers'] / (df['advancers'] + df['decliners'])
df

sign                       decliners  unchanged  advancers  percent_advancing
timestamp
2018-12-03 05:00:00+00:00       1016          1       1066           0.512008
2018-12-04 05:00:00+00:00       1748         55        281           0.138492
2018-12-06 05:00:00+00:00       1202         75        808           0.401990
2018-12-07 05:00:00+00:00       1496         91        498           0.249749
2018-12-10 05:00:00+00:00       1366         84        636           0.317682
2018-12-11 05:00:00+00:00       1155         91        840           0.421053
2018-12-12 05:00:00+00:00        654         79       1354           0.674303
2018-12-13 05:00:00+00:00       1317         97        673           0.338191
2018-12-14 05:00:00+00:00       1642         89        356           0.178178
2018-12-17 05:00:00+00:00       1770         67        250           0.123762
2018-12-18 05:00:00+00:00       1032         86        969           0.484258
2018-12-19 05:00:00+00:00       1574         66        448           0.221563
2018-12-20 05:00:00+00:00       1651         76        362           0.179831
2018-12-21 05:00:00+00:00       1653         65        371           0.183300
2018-12-24 05:00:00+00:00       1597         89        404           0.201899
2018-12-26 05:00:00+00:00        195         69       1826           0.903513
2018-12-27 05:00:00+00:00        824         94       1172           0.587174
2018-12-28 05:00:00+00:00        873         87       1131           0.564371
2018-12-31 05:00:00+00:00        590         75       1426           0.707341
2019-01-02 05:00:00+00:00        702         69       1321           0.652991
2019-01-03 05:00:00+00:00       1301         83        708           0.352414
2019-01-04 05:00:00+00:00        165         66       1861           0.918559
2019-01-07 05:00:00+00:00        405         57       1630           0.800983
2019-01-08 05:00:00+00:00        368         72       1652           0.817822
2019-01-09 05:00:00+00:00        527         95       1470           0.736104
2019-01-10 05:00:00+00:00        729         99       1264           0.634220

In [ ]:
df['ema'] = df['percent_advancing'].ewm(span=10, adjust=False).mean()
df

sign,decliners,unchanged,advancers,percent_advancing,ema
timestamp,,,,,
2018-12-03 05:00:00+00:00,1016,1,1066,0.512008,0.512008
2018-12-04 05:00:00+00:00,1748,55,281,0.138492,0.444096
2018-12-06 05:00:00+00:00,1202,75,808,0.401990,0.436440
2018-12-07 05:00:00+00:00,1496,91,498,0.249749,0.402496
2018-12-10 05:00:00+00:00,1366,84,636,0.317682,0.387076
2018-12-11 05:00:00+00:00,1155,91,840,0.421053,0.393253
2018-12-12 05:00:00+00:00,654,79,1354,0.674303,0.444353
2018-12-13 05:00:00+00:00,1317,97,673,0.338191,0.425051
2018-12-14 05:00:00+00:00,1642,89,356,0.178178,0.380165
2018-12-17 05:00:00+00:00,1770,67,250,0.123762,0.333546
2018-12-18 05:00:00+00:00,1032,86,969,0.484258,0.360948
2018-12-19 05:00:00+00:00,1574,66,448,0.221563,0.335606
2018-12-20 05:00:00+00:00,1651,76,362,0.179831,0.307283
2018-12-21 05:00:00+00:00,1653,65,371,0.183300,0.284741
2018-12-24 05:00:00+00:00,1597,89,404,0.201899,0.269679
2018-12-26 05:00:00+00:00,195,69,1826,0.903513,0.384921
2018-12-27 05:00:00+00:00,824,94,1172,0.587174,0.421695
2018-12-28 05:00:00+00:00,873,87,1131,0.564371,0.447636
2018-12-31 05:00:00+00:00,590,75,1426,0.707341,0.494855
2019-01-02 05:00:00+00:00,702,69,1321,0.652991,0.523607
2019-01-03 05:00:00+00:00,1301,83,708,0.352414,0.492481
2019-01-04 05:00:00+00:00,165,66,1861,0.918559,0.569950
2019-01-07 05:00:00+00:00,405,57,1630,0.800983,0.611956
2019-01-08 05:00:00+00:00,368,72,1652,0.817822,0.649386
2019-01-09 05:00:00+00:00,527,95,1470,0.736104,0.665153
2019-01-10 05:00:00+00:00,729,99,1264,0.634220,0.659529

# Breakaway Momentum

According to Walter Deemer, [Breakaway Momentum](https://www.walterdeemer.com/bam.htm) occurs when the 10 day EMA of the Advance/Decline ratio exceeds 1.97. He provides a table of occurrences on his website, linked above.

![](https://i.imgur.com/DjFJ4jK.png)

Since our list of NYSE traded symbols is from today, let's look at the most recent occurrence from June 2020. Note this occurrence is unsual in that it occurred when the market was already in an uptrend. This suggested that there was another leg up in the bull market.

In [ ]:
bars = alpaca.get_bars(symbols, TimeFrame.Day, "2020-05-01", "2020-06-10").df
bars['pct_change'] = bars['close'].pct_change()
bars['sign'] = np.sign(bars['pct_change'])
df = bars.groupby(by = ['timestamp', 'sign'])['sign'].count().to_frame('count').reset_index()
df = pandas.pivot_table(df, values = 'count', index=['timestamp'], columns = 'sign')
df = df.rename(columns={1.0: "advancers", 0.0: "unchanged", -1.0: "decliners"})
df['10dayadvancers'] = df['advancers'].rolling(window=10).sum()
df['10daydecliners'] = df['decliners'].rolling(window=10).sum()
df['bam'] = df['10dayadvancers'] / df['10daydecliners']
df

sign,decliners,unchanged,advancers,10dayadvancers,10daydecliners,bam
timestamp,,,,,,
2020-05-01 04:00:00+00:00,1219.0,NaN,990.0,NaN,NaN,NaN
2020-05-04 04:00:00+00:00,1151.0,94.0,965.0,NaN,NaN,NaN
2020-05-05 04:00:00+00:00,894.0,88.0,1228.0,NaN,NaN,NaN
2020-05-06 04:00:00+00:00,1494.0,100.0,616.0,NaN,NaN,NaN
2020-05-07 04:00:00+00:00,522.0,97.0,1591.0,NaN,NaN,NaN
2020-05-08 04:00:00+00:00,294.0,79.0,1837.0,NaN,NaN,NaN
2020-05-11 04:00:00+00:00,1462.0,97.0,651.0,NaN,NaN,NaN
2020-05-12 04:00:00+00:00,1723.0,89.0,398.0,NaN,NaN,NaN
2020-05-13 04:00:00+00:00,1931.0,68.0,211.0,NaN,NaN,NaN
2020-05-14 04:00:00+00:00,920.0,80.0,1210.0,9697.0,11610.0,0.835228
2020-05-15 04:00:00+00:00,860.0,104.0,1247.0,9954.0,11251.0,0.884721
2020-05-18 04:00:00+00:00,184.0,70.0,1956.0,10945.0,10284.0,1.064275
2020-05-19 04:00:00+00:00,1415.0,96.0,699.0,10416.0,10805.0,0.963998
2020-05-20 04:00:00+00:00,356.0,77.0,1777.0,11577.0,9667.0,1.197579
2020-05-21 04:00:00+00:00,1084.0,92.0,1035.0,11021.0,10229.0,1.077427
2020-05-22 04:00:00+00:00,956.0,105.0,1150.0,10334.0,10891.0,0.948857
2020-05-26 04:00:00+00:00,302.0,73.0,1836.0,11519.0,9731.0,1.183743
2020-05-27 04:00:00+00:00,353.0,81.0,1777.0,12898.0,8361.0,1.542638
2020-05-28 04:00:00+00:00,1328.0,87.0,796.0,13483.0,7758.0,1.737948
2020-05-29 04:00:00+00:00,1201.0,75.0,935.0,13208.0,8039.0,1.642990
2020-06-01 04:00:00+00:00,498.0,73.0,1640.0,13601.0,7677.0,1.771656
2020-06-02 04:00:00+00:00,508.0,85.0,1618.0,13263.0,8001.0,1.657668
2020-06-03 04:00:00+00:00,376.0,79.0,1758.0,14322.0,6962.0,2.057167
2020-06-04 04:00:00+00:00,973.0,81.0,1159.0,13704.0,7579.0,1.808154
2020-06-05 04:00:00+00:00,281.0,70.0,1864.0,14533.0,6776.0,2.144776
2020-06-08 04:00:00+00:00,397.0,79.0,1739.0,15122.0,6217.0,2.432363
2020-06-09 04:00:00+00:00,1777.0,78.0,360.0,13646.0,7692.0,1.774051
2020-06-10 04:00:00+00:00,1657.0,83.0,475.0,12344.0,8996.0,1.372165

# Whaley Breadth Thrust

The Whaley Breadth Thrust is described in the paper [Planes, Trains, and Automobiles](https://lindaraschke.net/wp-content/uploads/Whaley-Breadth-THrust.pdf). It uses the 5 day sum of advances divided by the 5 day sum of advances and declines. Percentages above 70 percent are statistically significant and percentages above 75% have a perfect track record.

![](https://i.imgur.com/oVuuRmg.png)

In [ ]:
df['5dayadvancers'] = df['advancers'].rolling(window=5).sum()
df['5daydecliners'] = df['decliners'].rolling(window=5).sum()
df['whaley_percent'] = df['5dayadvancers'] / (df['5dayadvancers'] + df['5daydecliners'])
df

sign,decliners,unchanged,advancers,5dayadvancers,5daydecliners,whaley_percent
timestamp,,,,,,
2020-05-01 04:00:00+00:00,1216.0,NaN,992.0,NaN,NaN,NaN
2020-05-04 04:00:00+00:00,1150.0,94.0,965.0,NaN,NaN,NaN
2020-05-05 04:00:00+00:00,897.0,88.0,1224.0,NaN,NaN,NaN
2020-05-06 04:00:00+00:00,1493.0,100.0,616.0,NaN,NaN,NaN
2020-05-07 04:00:00+00:00,522.0,97.0,1590.0,5387.0,5278.0,0.505110
2020-05-08 04:00:00+00:00,294.0,79.0,1836.0,6231.0,4356.0,0.588552
2020-05-11 04:00:00+00:00,1462.0,97.0,650.0,5916.0,4668.0,0.558957
2020-05-12 04:00:00+00:00,1723.0,89.0,397.0,5089.0,5494.0,0.480866
2020-05-13 04:00:00+00:00,1931.0,68.0,210.0,4683.0,5932.0,0.441168
2020-05-14 04:00:00+00:00,919.0,80.0,1210.0,4303.0,6329.0,0.404722
2020-05-15 04:00:00+00:00,860.0,103.0,1247.0,3714.0,6895.0,0.350080
2020-05-18 04:00:00+00:00,183.0,70.0,1956.0,5020.0,5616.0,0.471982
2020-05-19 04:00:00+00:00,1414.0,96.0,699.0,5322.0,5307.0,0.500706
2020-05-20 04:00:00+00:00,356.0,76.0,1777.0,6889.0,3732.0,0.648621
2020-05-21 04:00:00+00:00,1083.0,92.0,1035.0,6714.0,3896.0,0.632799
2020-05-22 04:00:00+00:00,956.0,104.0,1150.0,6617.0,3992.0,0.623716
2020-05-26 04:00:00+00:00,302.0,73.0,1835.0,6496.0,4111.0,0.612426
2020-05-27 04:00:00+00:00,355.0,81.0,1774.0,7571.0,3052.0,0.712699
2020-05-28 04:00:00+00:00,1328.0,87.0,795.0,6589.0,4024.0,0.620842
2020-05-29 04:00:00+00:00,1200.0,75.0,935.0,6489.0,4141.0,0.610442
2020-06-01 04:00:00+00:00,497.0,73.0,1640.0,6979.0,3682.0,0.654629
2020-06-02 04:00:00+00:00,507.0,84.0,1619.0,6763.0,3887.0,0.635023
2020-06-03 04:00:00+00:00,372.0,79.0,1761.0,6750.0,3904.0,0.633565
2020-06-04 04:00:00+00:00,973.0,81.0,1158.0,7113.0,3549.0,0.667136
2020-06-05 04:00:00+00:00,280.0,70.0,1864.0,8042.0,2629.0,0.753631
2020-06-08 04:00:00+00:00,399.0,79.0,1736.0,8138.0,2531.0,0.762771
2020-06-09 04:00:00+00:00,1776.0,77.0,361.0,6880.0,3800.0,0.644195
2020-06-10 04:00:00+00:00,1657.0,82.0,475.0,5594.0,5085.0,0.523832